name: ferenckiss_census_demo

profile: ferenckiss_census_demo

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  ferenckiss_census_demo:
    +schema: raw

models:
  ferenckiss_census_demo:
    # Materialize staging models as views, and marts as tables
    staging:
      +schema: analytics_staging
      +materialized: view
    intermediate:
      +schema: analytics_intermediate
      +materialized: table
    marts:
      +schema: analytics_mart
      +materialized: table
